### ISSUE TITLE
The nodejs server returns 200 for random URLs

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-code-manager#1661]
### Describe the problem and steps to reproduce it:

It appears that the nodejs server of this code repo returns 200 for any random URLs. For example,

```
$ curl -I https://code.addons.mozilla.org/a/random/url/like/this
HTTP/1.1 200 OK
cache-control: private, no-store
Content-Length: 968
Content-Security-Policy: default-src 'none'; child-src 'none'; connect-src https://addons.mozilla.org https://www.google-analytics.com https://sentry.prod.mozaws.net; base-uri 'self'; font-src 'none'; form-action 'none'; frame-ancestors 'none'; frame-src 'none'; img-src https://addons-code-manager.cdn.mozilla.net/static/ https://reviewers.addons.mozilla.org/en-US/reviewers/download-git-file/; manifest-src 'none'; media-src 'none'; object-src 'none'; script-src https://addons-code-manager.cdn.mozilla.net/static/ https://www.google-analytics.com/analytics.js; style-src https://addons-code-manager.cdn.mozilla.net/static/; worker-src 'none'; report-uri https://addons.mozilla.org/__cspreport__
Content-Type: text/html; charset=utf-8
Date: Thu, 23 Jul 2020 00:30:02 GMT
ETag: W/"3c8-Jg3J43L70OlE6EzsjFhGqYtcgG0"
Public-Key-Pins: max-age=5184000; includeSubDomains; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

This is an issue for at least a few reasons, afaict,

1. The standard server side behavior should be returning 404 for non-existing URLs, and we should follow that standard.
2. Anyone can freely explore the server side URLs and as a result it messes up our monitoring dashboard. For example, we monitor the 200s for successful request rate and with everything 200, it renders that monitoring data point useless.
3. waste of server side cpu cycles.

### What happened?

As stated above.

### What did you expect to happen?

For URLs the nodejs server doesn't service, it should return 404.

### Anything else we should know?

Just FYI that currently Nginx proxies everything under `/` to the nodejs server, as can be seen [here](https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.code_manager.conf.erb#L18-L20).

It is an option that we only proxy known urls to the nodejs server, and return 404 for others. Another option is for the nodejs code to decide what to return 404 and what to return 200 for.

Please let me know what you think.

---

**For QA:** all valid code-manager URLs should load fine, either directly or when navigating on a page (after the initial page has been loaded). Invalid URLs should be rejected by Nginx (404).

**Comment by bobsilverberg** [comment]
What do you think, @willdurand? Should we just have nginx take care of this? There are really only two valid paths for code manager, afaict.

**Comment by willdurand** [comment]
I think we can reduce the priority first, this is an almost pure client side app so having a catch all endpoint makes sense, otherwise routing would be broken. Maintaining routing in the app as well as in the node server seems unnecessary to me.

I'd rely on nginx for that becausd we have only 2 URLs and it's unlikely that we will have a lot more in the future. in code manager, we could add a comment here: https://github.com/mozilla/addons-code-manager/blob/597ba019893f31505d6830a6ee4a7cfa317d9671/src/components/App/index.tsx#L153

(about the need to update the nginx config for new routes)

**Comment by bobsilverberg** [comment]
Thanks @willdurand.

 @bqbn seemed particularly concerned about this, which is why I made it a P2. We can drop the priority, or we can just do it. ;-)

If we're going the nginx route (pardon the pun), then is all we (engineering) need to do is add that comment you mentioned?

**Comment by willdurand** [comment]
> If we're going the nginx route (pardon the pun), then is all we (engineering) need to do is add that comment you mentioned?

Yep. Although we could also submit a PR to the cloudops repo with the nginx changes.

**Comment by bqbn** [comment]
So, is it correct that Nginx should only proxy the following 2 path?

* exact match: `/`
* prefix match: `/:lang/browse/:addonId/versions/`

**Comment by bqbn** [comment]
A follow up question, what regex pattern can we use to match `:lang`? 

And we plan to use https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/urls.py#L9 to match `:addonId` if that's correct.

**Comment by willdurand** [comment]
> So, is it correct that Nginx should only proxy the following 2 path?
> 
>     * exact match: `/`
> 
>     * prefix match: `/:lang/browse/:addonId/versions/`

According to https://github.com/mozilla/addons-code-manager/blob/597ba019893f31505d6830a6ee4a7cfa317d9671/src/components/App/index.tsx#L153-L166 there are 3 URL paths:

- `/`
- `/:lang/browse/:addonId/versions/:versionId/`
- `/:lang/compare/:addonId/versions/:baseVersionId...:headVersionId/`

`:lang` is currently only `en-US` so we could potentially use this value in nginx for now otherwise it should be a locale like what we have for addons-server/addons-frontend.

`:versionId`, `:baseVersionId` and `:headVersionId` should be numeric IDs (strictly positive numbers).

`:addonId` should also be a numeric ID *but* it might also work with any other ID (like GUID or slug), although I haven't tried. I think we can restrict the possible value to strictly positive numbers as well, though.

**Comment by bqbn** [comment]
We've deployed the nginx change in https://github.com/mozilla-services/cloudops-deployment/pull/3968 to -dev and -stage.

Please have it test and let us know if there are any regression issues.

**Comment by bobsilverberg** [comment]
When I visit an invalid URL on dev and stage, I now see a generic nginx 404 page:

<img width="865" alt="Screenshot 2020-07-31 08 42 26" src="https://user-images.githubusercontent.com/142755/89035952-d3373b00-d309-11ea-9135-fd918073aedd.png">

Is that what we want? I know the point is to not hand off processing to the node server, but is there a way for us to display something a bit more friendly?

**Comment by willdurand** [comment]
> When I visit an invalid URL on dev and stage, I now see a generic nginx 404 page:

I think this only happens when we load the invalid URL, right? If so, I think that's what we want. 404 generated from the client side would still get the (nicer?) code-manager 404 page.

**Comment by bobsilverberg** [comment]
> > When I visit an invalid URL on dev and stage, I now see a generic nginx 404 page:
> 
> I think this only happens when we load the invalid URL, right? If so, I think that's what we want. 404 generated from the client side would still get the (nicer?) code-manager 404 page.

Well, we should theoretically never get a 404 because of an invalid route on the client, unless there's a bug, right? I'm just a bit surprised that this 404 page is so ugly and uninformative. I guess we'd never expect anyone to see it except someone doing nefarious things though.

**Comment by willdurand** [comment]
> Well, we should theoretically never get a 404 because of an invalid route on the client, unless there's a bug, right?

Yes.

> I'm just a bit surprised that this 404 page is so ugly and uninformative. I guess we'd never expect anyone to see it except someone doing nefarious things though.

If we want a custom 404 page, that will either mean adding a static HTML page in the ops repo or serve a 404 from our node server, but that sort of defeats the purpose of what we want to achieve here, no?

code-manager isn't really a public tool so I think it's fine to have the default nginx error page. That's mainly to tell folks using spider tools that there is nothing to crawl here.

**Comment by bobsilverberg** [comment]
I agree it's probably fine.

**Comment by AlexandraMoga** [comment]
I've verified multiple browse and compare pages both by client side navigation and by direct link access and the tools is working as before.

A 404 error  caused by an invalid API request (by using some invalid version Id for example) is still displayed by code-manager:
![image](https://user-images.githubusercontent.com/31961530/89431696-ec484d80-d748-11ea-9905-d1bec39dd6a9.png)

A 404 error caused by some invalid URL patterns (like typos in `/browse/` or `/versions/`) will be displayed by nginx:
![image](https://user-images.githubusercontent.com/31961530/89431613-d6d32380-d748-11ea-9d5b-b0aed3cd276a.png)
